apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: splunk
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
     app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
      - name: splunk
        image: splunk/splunk:7.2.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: SPLUNK_START_ARGS
            value: --accept-license
          - name: SPLUNK_PASSWORD
            value: Varnost@2018!
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8089
          name: splunkd
        readinessProbe:
          httpGet:
            path: /en-US/account/login
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 10
        volumeMounts:
        - name: etc
          mountPath: /opt/splunk/etc
      volumes:
      - name: etc
        persistentVolumeClaim:
         claimName: splunk-etc